ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U5';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U6';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U7';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U9';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'U11';
