import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const ROUND_DATE: Record<number, string> = {
  1:"2026-05-02",2:"2026-05-09",3:"2026-05-16",4:"2026-05-23",5:"2026-05-30",
  6:"2026-06-13",7:"2026-06-20",8:"2026-06-27",9:"2026-07-04",10:"2026-07-18",
  11:"2026-07-25",12:"2026-08-01",13:"2026-08-08",14:"2026-08-15",15:"2026-08-22",
};

const P: Record<string,string> = {
  B1:"fww-bp-1",B2:"fww-bp-2",B3:"fww-bp-3",B4:"fww-bp-4",B5:"fww-bp-5",
  B6:"fww-bp-6",B7:"fww-bp-7",B8:"fww-bp-8",B9:"fww-bp-9",B10:"fww-bp-10",
  B11:"fww-bp-11",B12:"fww-bp-12",B13:"fww-bp-13",B14:"fww-bp-14",B15:"fww-bp-15",
  D1:"fww-dok-1",D2:"fww-dok-2",D3:"fww-dok-3",D4:"fww-dok-4",D5:"fww-dok-5",
  BU:"fww-burns-1",TP:"fww-bull-1",
};

function dt(round: number, hhmm: string): Date {
  return new Date(`${ROUND_DATE[round]}T${hhmm}:00+10:00`);
}
function tid(compId: string, name: string): string {
  return `${compId}--${name.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/-+$/,"")}`;
}
type FRow = [number, string, string, string];

async function seedComp(
  compId: string, name: string, ageGroup: string, gender: string,
  hhmm: string, slotPitch: string, teams: string[], rows: FRow[]
): Promise<void> {
  await prisma.competition.upsert({
    where:{id:compId}, update:{},
    create:{id:compId,name,season:"2026",ageGroup:ageGroup as any,gender:gender as any,status:"ACTIVE"},
  });
  await prisma.competitionTimeSlot.deleteMany({where:{competitionId:compId}});
  await prisma.competitionTimeSlot.create({
    data:{competitionId:compId,pitchId:P[slotPitch],dayOfWeek:6,startTime:hhmm,durationMins:40},
  });
  for (const t of teams) {
    const id = tid(compId,t);
    await prisma.team.upsert({where:{id},update:{},create:{id,name:t}});
    await prisma.competitionTeam.upsert({
      where:{competitionId_teamId:{competitionId:compId,teamId:id}},
      update:{},create:{competitionId:compId,teamId:id},
    });
  }
  await prisma.fixture.deleteMany({where:{competitionId:compId}});
  for (const [round,pk,home,away] of rows) {
    await prisma.fixture.create({data:{
      competitionId:compId,
      homeTeamId:tid(compId,home),
      awayTeamId:tid(compId,away),
      pitchId:P[pk],
      scheduledAt:dt(round,hhmm),
      round, status:"SCHEDULED",
    }});
  }
}

async function main() {
  // 1. Venues + pitches
  await prisma.venue.upsert({
    where:{id:"fww-bolton-park"}, update:{mapImage:"/bolton-park-map.jpg"},
    create:{id:"fww-bolton-park",name:"Bolton Park",address:"Cnr Bourke & Tompson Streets, Wagga Wagga NSW 2650",mapImage:"/bolton-park-map.jpg"},
  });
  for (let i = 1; i <= 15; i++) {
    await prisma.pitch.upsert({
      where:{id:`fww-bp-${i}`}, update:{},
      create:{id:`fww-bp-${i}`,name:`Field ${i}`,venueId:"fww-bolton-park"},
    });
  }

  await prisma.venue.upsert({
    where:{id:"fww-duke-of-kent"}, update:{},
    create:{id:"fww-duke-of-kent",name:"Duke of Kent Park",address:"Duke of Kent Drive, Wagga Wagga NSW 2650",mapImage:"/duke-of-kent-map.jpg"},
  });
  for (let i = 1; i <= 5; i++) {
    await prisma.pitch.upsert({
      where:{id:`fww-dok-${i}`}, update:{},
      create:{id:`fww-dok-${i}`,name:`Field ${i}`,venueId:"fww-duke-of-kent"},
    });
  }

  await prisma.venue.upsert({
    where:{id:"fww-burns-park-junee"}, update:{},
    create:{id:"fww-burns-park-junee",name:"Burns Park",address:"Junee NSW"},
  });
  await prisma.pitch.upsert({
    where:{id:"fww-burns-1"}, update:{},
    create:{id:"fww-burns-1",name:"Field 1",venueId:"fww-burns-park-junee"},
  });

  await prisma.venue.upsert({
    where:{id:"fww-bull-paddock-tumut"}, update:{},
    create:{id:"fww-bull-paddock-tumut",name:"Bull Paddock",address:"Tumut NSW"},
  });
  await prisma.pitch.upsert({
    where:{id:"fww-bull-1"}, update:{},
    create:{id:"fww-bull-1",name:"Field 1",venueId:"fww-bull-paddock-tumut"},
  });

  // 2. Admin user
  const passwordHash = await bcrypt.hash("ChangeMe123!", 10);
  await prisma.user.upsert({
    where:{email:"development@footballwagga.com.au"}, update:{},
    create:{email:"development@footballwagga.com.au",name:"Liam Dedini",passwordHash,role:"ADMIN"},
  });

  // 3. Competitions

  // --- 1. U5 Black ---
  await seedComp(
    "fww-u5-black","U5 Black","U5","MIXED","13:15","B1",
    ["South Wagga Vikings","South Wagga Warriors","Lake Albert Black","Lake Albert Red","Lake Albert White","Lake Albert Mako","Wagga United Ravens","Wagga United Crows","Henwood Park Eagles","Henwood Park Falcons","Henwood Park Hawks","Tolland Wolves","Junee"],
    [
      [1,"B1","South Wagga Vikings","Tolland Wolves"],
      [1,"B2","Lake Albert Black","Wagga United Ravens"],
      [1,"B3","Lake Albert Red","Wagga United Crows"],
      [1,"B4","Lake Albert White","Henwood Park Eagles"],
      [1,"B5","Lake Albert Mako","Henwood Park Falcons"],
      [1,"BU","Junee","Henwood Park Hawks"],
      [2,"B1","South Wagga Warriors","Tolland Wolves"],
      [2,"B2","South Wagga Vikings","Wagga United Crows"],
      [2,"B3","Lake Albert Black","Henwood Park Eagles"],
      [2,"B4","Lake Albert Red","Henwood Park Falcons"],
      [2,"B5","Lake Albert White","Henwood Park Hawks"],
      [2,"B6","Lake Albert Mako","Junee"],
      [3,"B1","South Wagga Warriors","Wagga United Ravens"],
      [3,"B2","Tolland Wolves","Wagga United Crows"],
      [3,"B3","South Wagga Vikings","Henwood Park Falcons"],
      [3,"B4","Lake Albert Black","Henwood Park Hawks"],
      [3,"BU","Junee","Lake Albert Red"],
      [3,"B6","Lake Albert White","Lake Albert Mako"],
      [4,"B1","South Wagga Warriors","Wagga United Crows"],
      [4,"B2","Wagga United Ravens","Henwood Park Eagles"],
      [4,"B3","Tolland Wolves","Henwood Park Falcons"],
      [4,"B4","South Wagga Vikings","Junee"],
      [4,"B5","Lake Albert Black","Lake Albert Mako"],
      [4,"B6","Lake Albert Red","Lake Albert White"],
      [5,"B1","South Wagga Warriors","Henwood Park Eagles"],
      [5,"B2","Wagga United Crows","Henwood Park Falcons"],
      [5,"B3","Wagga United Ravens","Henwood Park Hawks"],
      [5,"BU","Junee","Tolland Wolves"],
      [5,"B5","South Wagga Vikings","Lake Albert White"],
      [5,"B6","Lake Albert Black","Lake Albert Red"],
      [6,"B1","South Wagga Warriors","Henwood Park Falcons"],
      [6,"B2","Henwood Park Eagles","Henwood Park Hawks"],
      [6,"B3","Wagga United Crows","Junee"],
      [6,"B4","Wagga United Ravens","Lake Albert Mako"],
      [6,"B5","Tolland Wolves","Lake Albert White"],
      [6,"B6","South Wagga Vikings","Lake Albert Black"],
      [7,"B1","South Wagga Warriors","Henwood Park Hawks"],
      [7,"BU","Junee","Henwood Park Falcons"],
      [7,"B3","Henwood Park Eagles","Lake Albert Mako"],
      [7,"B4","Wagga United Crows","Lake Albert White"],
      [7,"B5","Wagga United Ravens","Lake Albert Red"],
      [7,"B6","Tolland Wolves","Lake Albert Black"],
      [8,"B1","South Wagga Warriors","Junee"],
      [8,"B2","Henwood Park Hawks","Lake Albert Mako"],
      [8,"B3","Henwood Park Falcons","Lake Albert White"],
      [8,"B4","Henwood Park Eagles","Lake Albert Red"],
      [8,"B5","Wagga United Crows","Lake Albert Black"],
      [8,"B6","Wagga United Ravens","South Wagga Vikings"],
      [9,"B1","South Wagga Warriors","Lake Albert Mako"],
      [9,"BU","Junee","Lake Albert White"],
      [9,"B3","Henwood Park Hawks","Lake Albert Red"],
      [9,"B4","Henwood Park Falcons","Lake Albert Black"],
      [9,"B5","Henwood Park Eagles","South Wagga Vikings"],
      [9,"B6","Wagga United Ravens","Tolland Wolves"],
      [10,"B1","South Wagga Warriors","Lake Albert White"],
      [10,"B2","Lake Albert Mako","Lake Albert Red"],
      [10,"B3","Junee","Lake Albert Black"],
      [10,"B4","Henwood Park Hawks","South Wagga Vikings"],
      [10,"B5","Henwood Park Eagles","Tolland Wolves"],
      [10,"B6","Wagga United Crows","Wagga United Ravens"],
      [11,"B1","South Wagga Warriors","Lake Albert Red"],
      [11,"B2","Lake Albert White","Lake Albert Black"],
      [11,"B3","Lake Albert Mako","South Wagga Vikings"],
      [11,"B4","Henwood Park Hawks","Tolland Wolves"],
      [11,"B5","Henwood Park Falcons","Wagga United Ravens"],
      [11,"B6","Henwood Park Eagles","Wagga United Crows"],
      [12,"B1","South Wagga Warriors","Lake Albert Black"],
      [12,"B2","Lake Albert Red","South Wagga Vikings"],
      [12,"B3","Lake Albert Mako","Tolland Wolves"],
      [12,"B4","Junee","Wagga United Ravens"],
      [12,"B5","Henwood Park Hawks","Wagga United Crows"],
      [12,"B6","Henwood Park Falcons","Henwood Park Eagles"],
      [13,"B1","South Wagga Warriors","South Wagga Vikings"],
      [13,"B2","Lake Albert Red","Tolland Wolves"],
      [13,"B3","Lake Albert White","Wagga United Ravens"],
      [13,"B4","Lake Albert Mako","Wagga United Crows"],
      [13,"BU","Junee","Henwood Park Eagles"],
      [13,"B6","Henwood Park Hawks","Henwood Park Falcons"],
      [14,"B1","South Wagga Vikings","Tolland Wolves"],
      [14,"B2","Lake Albert Black","Wagga United Ravens"],
      [14,"B3","Lake Albert Red","Wagga United Crows"],
      [14,"B4","Lake Albert White","Henwood Park Eagles"],
      [14,"B5","Lake Albert Mako","Henwood Park Falcons"],
      [14,"B6","Junee","Henwood Park Hawks"],
      [15,"B1","South Wagga Warriors","Tolland Wolves"],
      [15,"B2","South Wagga Vikings","Wagga United Crows"],
      [15,"B3","Lake Albert Black","Henwood Park Eagles"],
      [15,"B4","Lake Albert Red","Henwood Park Falcons"],
      [15,"B5","Lake Albert White","Henwood Park Hawks"],
      [15,"BU","Junee","Lake Albert Mako"],
    ]
  );

  // --- 2. U6 Black ---
  await seedComp(
    "fww-u6-black","U6 Black","U6","MIXED","09:15","B1",
    ["South Wagga Warriors","South Wagga Vikings","Tolland Wolves","Wagga United Rooks","Tumut Gold","Tumut Red","Henwood Park Falcons","Henwood Park BlackHawks","Henwood Park Hawks","Lake Albert Tiger","Lake Albert Red","Lake Albert Black","Lake Albert Mako","Junee Blue"],
    [
      [1,"B1","South Wagga Warriors","Tolland Wolves"],
      [1,"B2","South Wagga Vikings","Wagga United Rooks"],
      [1,"B3","Tumut Gold","Henwood Park Falcons"],
      [1,"B4","Tumut Red","Henwood Park BlackHawks"],
      [1,"B5","Lake Albert Tiger","Henwood Park Hawks"],
      [1,"BU","Junee Blue","Lake Albert Red"],
      [1,"B7","Lake Albert Black","Lake Albert Mako"],
      [2,"B1","South Wagga Warriors","Wagga United Rooks"],
      [2,"B2","Tolland Wolves","Henwood Park Falcons"],
      [2,"B3","South Wagga Vikings","Henwood Park BlackHawks"],
      [2,"TP","Tumut Gold","Henwood Park Hawks"],
      [2,"TP","Tumut Red","Junee Blue"],
      [2,"B6","Lake Albert Tiger","Lake Albert Mako"],
      [2,"B7","Lake Albert Red","Lake Albert Black"],
      [3,"B1","South Wagga Warriors","Henwood Park Falcons"],
      [3,"B2","Wagga United Rooks","Henwood Park BlackHawks"],
      [3,"B3","Tolland Wolves","Henwood Park Hawks"],
      [3,"BU","Junee Blue","South Wagga Vikings"],
      [3,"B5","Tumut Gold","Lake Albert Mako"],
      [3,"B6","Tumut Red","Lake Albert Black"],
      [3,"B7","Lake Albert Tiger","Lake Albert Red"],
      [4,"B1","South Wagga Warriors","Henwood Park Hawks"],
      [4,"B2","Henwood Park BlackHawks","Junee Blue"],
      [4,"B3","Henwood Park Falcons","Lake Albert Mako"],
      [4,"B4","Wagga United Rooks","Lake Albert Black"],
      [4,"B5","Tolland Wolves","Lake Albert Red"],
      [4,"B6","South Wagga Vikings","Lake Albert Tiger"],
      [4,"TP","Tumut Gold","Tumut Red"],
      [5,"B1","South Wagga Warriors","Henwood Park BlackHawks"],
      [5,"B2","Henwood Park Falcons","Henwood Park Hawks"],
      [5,"BU","Junee Blue","Wagga United Rooks"],
      [5,"B4","Tolland Wolves","Lake Albert Mako"],
      [5,"B5","South Wagga Vikings","Lake Albert Black"],
      [5,"B6","Tumut Gold","Lake Albert Red"],
      [5,"B7","Tumut Red","Lake Albert Tiger"],
      [6,"B1","South Wagga Warriors","Junee Blue"],
      [6,"B2","Henwood Park Hawks","Lake Albert Mako"],
      [6,"B3","Henwood Park BlackHawks","Lake Albert Black"],
      [6,"B4","Henwood Park Falcons","Lake Albert Red"],
      [6,"B5","Wagga United Rooks","Lake Albert Tiger"],
      [6,"TP","Tumut Red","Tolland Wolves"],
      [6,"TP","Tumut Gold","South Wagga Vikings"],
      [7,"B1","South Wagga Warriors","Lake Albert Mako"],
      [7,"BU","Junee Blue","Lake Albert Black"],
      [7,"B3","Henwood Park Hawks","Lake Albert Red"],
      [7,"B4","Henwood Park BlackHawks","Lake Albert Tiger"],
      [7,"B5","Henwood Park Falcons","Tumut Red"],
      [7,"B6","Wagga United Rooks","Tumut Gold"],
      [7,"B7","Tolland Wolves","South Wagga Vikings"],
      [8,"B1","South Wagga Warriors","Lake Albert Black"],
      [8,"B2","Lake Albert Mako","Lake Albert Red"],
      [8,"B3","Junee Blue","Lake Albert Tiger"],
      [8,"TP","Tumut Red","Henwood Park Hawks"],
      [8,"TP","Tumut Gold","Henwood Park BlackHawks"],
      [8,"B6","Henwood Park Falcons","South Wagga Vikings"],
      [8,"B7","Wagga United Rooks","Tolland Wolves"],
      [9,"B1","South Wagga Warriors","Lake Albert Red"],
      [9,"B2","Lake Albert Black","Lake Albert Tiger"],
      [9,"B3","Lake Albert Mako","Tumut Red"],
      [9,"BU","Junee Blue","Tumut Gold"],
      [9,"B5","Henwood Park Hawks","South Wagga Vikings"],
      [9,"B6","Henwood Park BlackHawks","Tolland Wolves"],
      [9,"B7","Henwood Park Falcons","Wagga United Rooks"],
      [10,"B1","South Wagga Warriors","Lake Albert Tiger"],
      [10,"TP","Tumut Red","Lake Albert Red"],
      [10,"TP","Tumut Gold","Lake Albert Black"],
      [10,"B4","Lake Albert Mako","South Wagga Vikings"],
      [10,"B5","Junee Blue","Tolland Wolves"],
      [10,"B6","Henwood Park Hawks","Wagga United Rooks"],
      [10,"B7","Henwood Park BlackHawks","Henwood Park Falcons"],
      [11,"B1","South Wagga Warriors","Tumut Red"],
      [11,"B2","Lake Albert Tiger","Tumut Gold"],
      [11,"B3","Lake Albert Red","South Wagga Vikings"],
      [11,"B4","Lake Albert Black","Tolland Wolves"],
      [11,"B5","Lake Albert Mako","Wagga United Rooks"],
      [11,"BU","Junee Blue","Henwood Park Falcons"],
      [11,"B7","Henwood Park Hawks","Henwood Park BlackHawks"],
      [12,"TP","Tumut Gold","South Wagga Warriors"],
      [12,"TP","Tumut Red","South Wagga Vikings"],
      [12,"B3","Lake Albert Tiger","Tolland Wolves"],
      [12,"B4","Lake Albert Red","Wagga United Rooks"],
      [12,"B5","Lake Albert Black","Henwood Park Falcons"],
      [12,"B6","Lake Albert Mako","Henwood Park BlackHawks"],
      [12,"B7","Junee Blue","Henwood Park Hawks"],
      [13,"B1","South Wagga Warriors","South Wagga Vikings"],
      [13,"B2","Tumut Gold","Tolland Wolves"],
      [13,"B3","Tumut Red","Wagga United Rooks"],
      [13,"B4","Lake Albert Tiger","Henwood Park Falcons"],
      [13,"B5","Lake Albert Red","Henwood Park BlackHawks"],
      [13,"B6","Lake Albert Black","Henwood Park Hawks"],
      [13,"BU","Junee Blue","Lake Albert Mako"],
      [14,"B1","South Wagga Warriors","Tolland Wolves"],
      [14,"B2","South Wagga Vikings","Wagga United Rooks"],
      [14,"TP","Tumut Gold","Henwood Park Falcons"],
      [14,"TP","Tumut Red","Henwood Park BlackHawks"],
      [14,"B5","Lake Albert Tiger","Henwood Park Hawks"],
      [14,"B6","Lake Albert Red","Junee Blue"],
      [14,"B7","Lake Albert Black","Lake Albert Mako"],
      [15,"B1","South Wagga Warriors","Wagga United Rooks"],
      [15,"B2","Tolland Wolves","Henwood Park Falcons"],
      [15,"B3","South Wagga Vikings","Henwood Park BlackHawks"],
      [15,"B4","Tumut Gold","Henwood Park Hawks"],
      [15,"BU","Junee Blue","Tumut Red"],
      [15,"B6","Lake Albert Tiger","Lake Albert Mako"],
      [15,"B7","Lake Albert Red","Lake Albert Black"],
    ]
  );

  // --- 3. U6 White ---
  await seedComp(
    "fww-u6-white","U6 White","U6","MIXED","10:15","B1",
    ["South Wagga Gladiators","South Wagga Knights","Tumut Blue","Henwood Park Raptors","Henwood Park RedHawks","Henwood Park Eagles","Henwood Park SeaHawks","Lake Albert White","Lake Albert Bull","Wagga United Crows","Wagga United Swifts","Junee Yellow","Tolland Pups","Tolland Cubs"],
    [
      [1,"B1","South Wagga Gladiators","Henwood Park Raptors"],
      [1,"B2","Tumut Blue","Henwood Park RedHawks"],
      [1,"B3","Lake Albert White","Wagga United Crows"],
      [1,"B4","Lake Albert Bull","Wagga United Swifts"],
      [1,"BU","Junee Yellow","Tolland Pups"],
      [1,"B5","South Wagga Knights","Tolland Cubs"],
      [1,"B6","Henwood Park Eagles","Henwood Park SeaHawks"],
      [2,"B1","Henwood Park RedHawks","South Wagga Gladiators"],
      [2,"B2","Wagga United Crows","Henwood Park Raptors"],
      [2,"TP","Tumut Blue","Wagga United Swifts"],
      [2,"B3","Tolland Pups","Lake Albert White"],
      [2,"B4","Tolland Cubs","Lake Albert Bull"],
      [2,"B5","Henwood Park SeaHawks","Junee Yellow"],
      [2,"B6","Henwood Park Eagles","South Wagga Knights"],
      [3,"B1","South Wagga Gladiators","Wagga United Crows"],
      [3,"B2","Henwood Park RedHawks","Wagga United Swifts"],
      [3,"B3","Henwood Park Raptors","Tolland Pups"],
      [3,"B4","Tumut Blue","Tolland Cubs"],
      [3,"B5","Lake Albert White","Henwood Park SeaHawks"],
      [3,"B6","Lake Albert Bull","Henwood Park Eagles"],
      [3,"BU","Junee Yellow","South Wagga Knights"],
      [4,"B1","Wagga United Swifts","South Wagga Gladiators"],
      [4,"B2","Tolland Pups","Wagga United Crows"],
      [4,"B3","Tolland Cubs","Henwood Park RedHawks"],
      [4,"B4","Henwood Park SeaHawks","Henwood Park Raptors"],
      [4,"TP","Tumut Blue","Henwood Park Eagles"],
      [4,"B5","South Wagga Knights","Lake Albert White"],
      [4,"B6","Junee Yellow","Lake Albert Bull"],
      [5,"B1","South Wagga Gladiators","Tolland Pups"],
      [5,"B2","Wagga United Swifts","Tolland Cubs"],
      [5,"B3","Wagga United Crows","Henwood Park SeaHawks"],
      [5,"B4","Henwood Park RedHawks","Henwood Park Eagles"],
      [5,"B5","Henwood Park Raptors","South Wagga Knights"],
      [5,"BU","Junee Yellow","Tumut Blue"],
      [5,"B6","Lake Albert White","Lake Albert Bull"],
      [6,"B1","Tolland Cubs","South Wagga Gladiators"],
      [6,"B2","Henwood Park SeaHawks","Tolland Pups"],
      [6,"B3","Henwood Park Eagles","Wagga United Swifts"],
      [6,"B4","South Wagga Knights","Wagga United Crows"],
      [6,"B5","Junee Yellow","Henwood Park RedHawks"],
      [6,"B6","Lake Albert Bull","Henwood Park Raptors"],
      [6,"TP","Tumut Blue","Lake Albert White"],
      [7,"B1","South Wagga Gladiators","Henwood Park SeaHawks"],
      [7,"B2","Tolland Cubs","Henwood Park Eagles"],
      [7,"B3","Tolland Pups","South Wagga Knights"],
      [7,"BU","Junee Yellow","Wagga United Swifts"],
      [7,"B4","Wagga United Crows","Lake Albert Bull"],
      [7,"B5","Henwood Park RedHawks","Lake Albert White"],
      [7,"B6","Henwood Park Raptors","Tumut Blue"],
      [8,"B1","Henwood Park Eagles","South Wagga Gladiators"],
      [8,"B2","South Wagga Knights","Henwood Park SeaHawks"],
      [8,"B3","Junee Yellow","Tolland Cubs"],
      [8,"B4","Lake Albert Bull","Tolland Pups"],
      [8,"B5","Lake Albert White","Wagga United Swifts"],
      [8,"TP","Tumut Blue","Wagga United Crows"],
      [8,"B6","Henwood Park Raptors","Henwood Park RedHawks"],
      [9,"B1","South Wagga Gladiators","South Wagga Knights"],
      [9,"BU","Junee Yellow","Henwood Park Eagles"],
      [9,"B2","Henwood Park SeaHawks","Lake Albert Bull"],
      [9,"B3","Tolland Cubs","Lake Albert White"],
      [9,"B4","Tolland Pups","Tumut Blue"],
      [9,"B5","Wagga United Swifts","Henwood Park Raptors"],
      [9,"B6","Wagga United Crows","Henwood Park RedHawks"],
      [10,"B1","Junee Yellow","South Wagga Gladiators"],
      [10,"B2","Lake Albert Bull","South Wagga Knights"],
      [10,"B3","Lake Albert White","Henwood Park Eagles"],
      [10,"TP","Tumut Blue","Henwood Park SeaHawks"],
      [10,"B4","Henwood Park Raptors","Tolland Cubs"],
      [10,"B5","Henwood Park RedHawks","Tolland Pups"],
      [10,"B6","Wagga United Crows","Wagga United Swifts"],
      [11,"B1","South Wagga Gladiators","Lake Albert Bull"],
      [11,"BU","Junee Yellow","Lake Albert White"],
      [11,"B2","South Wagga Knights","Tumut Blue"],
      [11,"B3","Henwood Park Eagles","Henwood Park Raptors"],
      [11,"B4","Henwood Park SeaHawks","Henwood Park RedHawks"],
      [11,"B5","Tolland Cubs","Wagga United Crows"],
      [11,"B6","Tolland Pups","Wagga United Swifts"],
      [12,"B1","Lake Albert White","South Wagga Gladiators"],
      [12,"TP","Tumut Blue","Lake Albert Bull"],
      [12,"B2","Henwood Park Raptors","Junee Yellow"],
      [12,"B3","Henwood Park RedHawks","South Wagga Knights"],
      [12,"B4","Wagga United Crows","Henwood Park Eagles"],
      [12,"B5","Wagga United Swifts","Henwood Park SeaHawks"],
      [12,"B6","Tolland Pups","Tolland Cubs"],
      [13,"B1","South Wagga Gladiators","Tumut Blue"],
      [13,"B2","Lake Albert White","Henwood Park Raptors"],
      [13,"B3","Lake Albert Bull","Henwood Park RedHawks"],
      [13,"BU","Junee Yellow","Wagga United Crows"],
      [13,"B4","South Wagga Knights","Wagga United Swifts"],
      [13,"B5","Henwood Park Eagles","Tolland Pups"],
      [13,"B6","Henwood Park SeaHawks","Tolland Cubs"],
      [14,"B1","South Wagga Gladiators","Henwood Park Raptors"],
      [14,"TP","Tumut Blue","Henwood Park RedHawks"],
      [14,"B2","Lake Albert White","Wagga United Crows"],
      [14,"B3","Lake Albert Bull","Wagga United Swifts"],
      [14,"B4","Junee Yellow","Tolland Pups"],
      [14,"B5","South Wagga Knights","Tolland Cubs"],
      [14,"B6","Henwood Park Eagles","Henwood Park SeaHawks"],
      [15,"B1","Henwood Park RedHawks","South Wagga Gladiators"],
      [15,"B2","Wagga United Crows","Henwood Park Raptors"],
      [15,"B3","Tumut Blue","Wagga United Swifts"],
      [15,"B4","Tolland Pups","Lake Albert White"],
      [15,"B5","Tolland Cubs","Lake Albert Bull"],
      [15,"BU","Junee Yellow","Henwood Park SeaHawks"],
      [15,"B6","Henwood Park Eagles","South Wagga Knights"],
    ]
  );

  // --- 4. U5/6 Girls ---
  await seedComp(
    "fww-u56-girls","U5/6 Girls","U6","FEMALE","13:15","B7",
    ["South Wagga Warriors","South Wagga Knights","Wagga United Kingfishers","Wagga United Robins","Tumut Gold","Lake Albert Red","Lake Albert Black"],
    [
      [1,"B7","Wagga United Kingfishers","Lake Albert Red"],
      [1,"B8","Wagga United Robins","Lake Albert Black"],
      [1,"B9","Tumut Gold","South Wagga Knights"],
      [2,"B7","South Wagga Warriors","Lake Albert Red"],
      [2,"B8","Wagga United Kingfishers","South Wagga Knights"],
      [2,"TP","Tumut Gold","Wagga United Robins"],
      [3,"B7","South Wagga Warriors","Lake Albert Black"],
      [3,"B8","Lake Albert Red","South Wagga Knights"],
      [3,"B9","Wagga United Kingfishers","Wagga United Robins"],
      [4,"B7","South Wagga Warriors","South Wagga Knights"],
      [4,"TP","Tumut Gold","Lake Albert Black"],
      [4,"B9","Lake Albert Red","Wagga United Robins"],
      [5,"B7","South Wagga Warriors","Tumut Gold"],
      [5,"B8","South Wagga Knights","Wagga United Robins"],
      [5,"B9","Lake Albert Black","Wagga United Kingfishers"],
      [6,"B7","South Wagga Warriors","Wagga United Robins"],
      [6,"TP","Tumut Gold","Wagga United Kingfishers"],
      [6,"B9","Lake Albert Black","Lake Albert Red"],
      [7,"B7","South Wagga Warriors","Wagga United Kingfishers"],
      [7,"B8","Tumut Gold","Lake Albert Red"],
      [7,"B9","South Wagga Knights","Lake Albert Black"],
      [8,"B7","Wagga United Kingfishers","Lake Albert Red"],
      [8,"B8","Wagga United Robins","Lake Albert Black"],
      [8,"TP","Tumut Gold","South Wagga Knights"],
      [9,"B7","South Wagga Warriors","Lake Albert Red"],
      [9,"B8","Wagga United Kingfishers","South Wagga Knights"],
      [9,"B9","Wagga United Robins","Tumut Gold"],
      [10,"B7","South Wagga Warriors","Lake Albert Black"],
      [10,"B8","Lake Albert Red","South Wagga Knights"],
      [10,"B9","Wagga United Kingfishers","Wagga United Robins"],
      [11,"B7","South Wagga Warriors","South Wagga Knights"],
      [11,"B8","Lake Albert Black","Tumut Gold"],
      [11,"B9","Lake Albert Red","Wagga United Robins"],
      [12,"TP","Tumut Gold","South Wagga Warriors"],
      [12,"B8","South Wagga Knights","Wagga United Robins"],
      [12,"B9","Lake Albert Black","Wagga United Kingfishers"],
      [13,"B7","South Wagga Warriors","Wagga United Robins"],
      [13,"B8","Tumut Gold","Wagga United Kingfishers"],
      [13,"B9","Lake Albert Black","Lake Albert Red"],
      [14,"B7","South Wagga Warriors","Wagga United Kingfishers"],
      [14,"TP","Tumut Gold","Lake Albert Red"],
      [14,"B9","South Wagga Knights","Lake Albert Black"],
      [15,"B7","Wagga United Kingfishers","Lake Albert Red"],
      [15,"B8","Wagga United Robins","Lake Albert Black"],
      [15,"B9","Tumut Gold","South Wagga Knights"],
    ]
  );

  // --- 5. U7 Black ---
  await seedComp(
    "fww-u7-black","U7 Black","U7","MIXED","11:15","B1",
    ["South Wagga Warriors","South Wagga Vikings","Tumut Gold","Wagga United Ravens","Wagga United Swifts","Lake Albert Red","Lake Albert Black","Lake Albert White","Henwood Park Raptors","Henwood Park Eagles","Henwood Park Falcons","Junee Blue","Tolland Pups","Tolland Wolves"],
    [
      [1,"B1","South Wagga Warriors","Tolland Pups"],
      [1,"B2","South Wagga Vikings","Tolland Wolves"],
      [1,"B3","Tumut Gold","Wagga United Ravens"],
      [1,"B4","Lake Albert Red","Wagga United Swifts"],
      [1,"B5","Lake Albert Black","Henwood Park Raptors"],
      [1,"B6","Lake Albert White","Henwood Park Eagles"],
      [1,"BU","Junee Blue","Henwood Park Falcons"],
      [2,"B1","South Wagga Warriors","Tolland Wolves"],
      [2,"B2","Tolland Pups","Wagga United Ravens"],
      [2,"B3","South Wagga Vikings","Wagga United Swifts"],
      [2,"TP","Tumut Gold","Henwood Park Raptors"],
      [2,"B5","Lake Albert Red","Henwood Park Eagles"],
      [2,"B6","Lake Albert Black","Henwood Park Falcons"],
      [2,"B7","Lake Albert White","Junee Blue"],
      [3,"B1","South Wagga Warriors","Wagga United Ravens"],
      [3,"B2","Tolland Wolves","Wagga United Swifts"],
      [3,"B3","Tolland Pups","Henwood Park Raptors"],
      [3,"B4","South Wagga Vikings","Henwood Park Eagles"],
      [3,"B5","Tumut Gold","Henwood Park Falcons"],
      [3,"BU","Junee Blue","Lake Albert Red"],
      [3,"B7","Lake Albert Black","Lake Albert White"],
      [4,"B1","South Wagga Warriors","Wagga United Swifts"],
      [4,"B2","Wagga United Ravens","Henwood Park Raptors"],
      [4,"B3","Tolland Wolves","Henwood Park Eagles"],
      [4,"B4","Tolland Pups","Henwood Park Falcons"],
      [4,"B5","South Wagga Vikings","Junee Blue"],
      [4,"TP","Tumut Gold","Lake Albert White"],
      [4,"B7","Lake Albert Red","Lake Albert Black"],
      [5,"B1","South Wagga Warriors","Henwood Park Raptors"],
      [5,"B2","Wagga United Swifts","Henwood Park Eagles"],
      [5,"B3","Wagga United Ravens","Henwood Park Falcons"],
      [5,"BU","Junee Blue","Tolland Wolves"],
      [5,"B5","Tolland Pups","Lake Albert White"],
      [5,"B6","South Wagga Vikings","Lake Albert Black"],
      [5,"B7","Tumut Gold","Lake Albert Red"],
      [6,"B1","South Wagga Warriors","Henwood Park Eagles"],
      [6,"B2","Henwood Park Raptors","Henwood Park Falcons"],
      [6,"B3","Wagga United Swifts","Junee Blue"],
      [6,"B4","Wagga United Ravens","Lake Albert White"],
      [6,"B5","Tolland Wolves","Lake Albert Black"],
      [6,"B6","Tolland Pups","Lake Albert Red"],
      [6,"TP","Tumut Gold","South Wagga Vikings"],
      [7,"B1","South Wagga Warriors","Henwood Park Falcons"],
      [7,"BU","Junee Blue","Henwood Park Eagles"],
      [7,"B3","Henwood Park Raptors","Lake Albert White"],
      [7,"B4","Wagga United Swifts","Lake Albert Black"],
      [7,"B5","Wagga United Ravens","Lake Albert Red"],
      [7,"B6","Tolland Wolves","Tumut Gold"],
      [7,"B7","Tolland Pups","South Wagga Vikings"],
      [8,"B1","South Wagga Warriors","Junee Blue"],
      [8,"B2","Henwood Park Falcons","Lake Albert White"],
      [8,"B3","Henwood Park Eagles","Lake Albert Black"],
      [8,"B4","Henwood Park Raptors","Lake Albert Red"],
      [8,"TP","Tumut Gold","Wagga United Swifts"],
      [8,"B6","Wagga United Ravens","South Wagga Vikings"],
      [8,"B7","Tolland Wolves","Tolland Pups"],
      [9,"B1","South Wagga Warriors","Lake Albert White"],
      [9,"BU","Junee Blue","Lake Albert Black"],
      [9,"B3","Henwood Park Falcons","Lake Albert Red"],
      [9,"B4","Henwood Park Eagles","Tumut Gold"],
      [9,"B5","Henwood Park Raptors","South Wagga Vikings"],
      [9,"B6","Wagga United Swifts","Tolland Pups"],
      [9,"B7","Wagga United Ravens","Tolland Wolves"],
      [10,"B1","South Wagga Warriors","Lake Albert Black"],
      [10,"B2","Lake Albert White","Lake Albert Red"],
      [10,"TP","Tumut Gold","Junee Blue"],
      [10,"B4","Henwood Park Falcons","South Wagga Vikings"],
      [10,"B5","Henwood Park Eagles","Tolland Pups"],
      [10,"B6","Henwood Park Raptors","Tolland Wolves"],
      [10,"B7","Wagga United Swifts","Wagga United Ravens"],
      [11,"B1","South Wagga Warriors","Lake Albert Red"],
      [11,"B2","Lake Albert Black","Tumut Gold"],
      [11,"B3","Lake Albert White","South Wagga Vikings"],
      [11,"BU","Junee Blue","Tolland Pups"],
      [11,"B5","Henwood Park Falcons","Tolland Wolves"],
      [11,"B6","Henwood Park Eagles","Wagga United Ravens"],
      [11,"B7","Henwood Park Raptors","Wagga United Swifts"],
      [12,"TP","Tumut Gold","South Wagga Warriors"],
      [12,"B2","Lake Albert Red","South Wagga Vikings"],
      [12,"B3","Lake Albert Black","Tolland Pups"],
      [12,"B4","Lake Albert White","Tolland Wolves"],
      [12,"B5","Junee Blue","Wagga United Ravens"],
      [12,"B6","Henwood Park Falcons","Wagga United Swifts"],
      [12,"B7","Henwood Park Eagles","Henwood Park Raptors"],
      [13,"B1","South Wagga Warriors","South Wagga Vikings"],
      [13,"B2","Tumut Gold","Tolland Pups"],
      [13,"B3","Lake Albert Red","Tolland Wolves"],
      [13,"B4","Lake Albert Black","Wagga United Ravens"],
      [13,"B5","Lake Albert White","Wagga United Swifts"],
      [13,"BU","Junee Blue","Henwood Park Raptors"],
      [13,"B7","Henwood Park Falcons","Henwood Park Eagles"],
      [14,"B1","South Wagga Warriors","Tolland Pups"],
      [14,"B2","South Wagga Vikings","Tolland Wolves"],
      [14,"TP","Tumut Gold","Wagga United Ravens"],
      [14,"B4","Lake Albert Red","Wagga United Swifts"],
      [14,"B5","Lake Albert Black","Henwood Park Raptors"],
      [14,"B6","Lake Albert White","Henwood Park Eagles"],
      [14,"B7","Junee Blue","Henwood Park Falcons"],
      [15,"B1","South Wagga Warriors","Tolland Wolves"],
      [15,"B2","Tolland Pups","Wagga United Ravens"],
      [15,"B3","South Wagga Vikings","Wagga United Swifts"],
      [15,"B4","Tumut Gold","Henwood Park Raptors"],
      [15,"B5","Lake Albert Red","Henwood Park Eagles"],
      [15,"B6","Lake Albert Black","Henwood Park Falcons"],
      [15,"BU","Junee Blue","Lake Albert White"],
    ]
  );

  // --- 6. U7 White ---
  await seedComp(
    "fww-u7-white","U7 White","U7","MIXED","12:15","B1",
    ["South Wagga Knights","South Wagga Gladiators","Junee Grey","Junee Yellow","Tolland Grey Wolves","Tolland Cubs","Tolland Lobos","Lake Albert Tiger","Lake Albert Bull","Lake Albert Pointer","Wagga United Crows","Henwood Park BlackHawks","Henwood Park Hawks"],
    [
      [1,"BU","Junee Grey","South Wagga Knights"],
      [1,"B2","South Wagga Gladiators","Tolland Grey Wolves"],
      [1,"B4","Lake Albert Tiger","Tolland Cubs"],
      [1,"B5","Lake Albert Bull","Wagga United Crows"],
      [1,"B6","Lake Albert Pointer","Henwood Park BlackHawks"],
      [1,"BU","Junee Yellow","Henwood Park Hawks"],
      [2,"B1","South Wagga Knights","Tolland Grey Wolves"],
      [2,"B2","Junee Grey","Tolland Lobos"],
      [2,"B3","South Wagga Gladiators","Tolland Cubs"],
      [2,"B5","Lake Albert Tiger","Henwood Park BlackHawks"],
      [2,"B6","Lake Albert Bull","Henwood Park Hawks"],
      [2,"B7","Junee Yellow","Lake Albert Pointer"],
      [3,"B1","South Wagga Knights","Tolland Lobos"],
      [3,"B2","Tolland Grey Wolves","Tolland Cubs"],
      [3,"BU","Junee Grey","Wagga United Crows"],
      [3,"B4","South Wagga Gladiators","Henwood Park BlackHawks"],
      [3,"BU","Junee Yellow","Lake Albert Tiger"],
      [3,"B7","Lake Albert Bull","Lake Albert Pointer"],
      [4,"B1","South Wagga Knights","Tolland Cubs"],
      [4,"B2","Tolland Lobos","Wagga United Crows"],
      [4,"B3","Tolland Grey Wolves","Henwood Park BlackHawks"],
      [4,"B4","Junee Grey","Henwood Park Hawks"],
      [4,"B5","South Wagga Gladiators","Junee Yellow"],
      [4,"B7","Lake Albert Tiger","Lake Albert Bull"],
      [5,"B1","South Wagga Knights","Wagga United Crows"],
      [5,"B2","Tolland Cubs","Henwood Park BlackHawks"],
      [5,"B3","Tolland Lobos","Henwood Park Hawks"],
      [5,"BU","Junee Yellow","Tolland Grey Wolves"],
      [5,"BU","Junee Grey","Lake Albert Pointer"],
      [5,"B6","South Wagga Gladiators","Lake Albert Bull"],
      [6,"B1","South Wagga Knights","Henwood Park BlackHawks"],
      [6,"B2","Wagga United Crows","Henwood Park Hawks"],
      [6,"B3","Tolland Cubs","Junee Yellow"],
      [6,"B4","Tolland Lobos","Lake Albert Pointer"],
      [6,"B5","Tolland Grey Wolves","Lake Albert Bull"],
      [6,"B6","Junee Grey","Lake Albert Tiger"],
      [7,"B1","South Wagga Knights","Henwood Park Hawks"],
      [7,"BU","Junee Yellow","Henwood Park BlackHawks"],
      [7,"B3","Wagga United Crows","Lake Albert Pointer"],
      [7,"B4","Tolland Cubs","Lake Albert Bull"],
      [7,"B5","Tolland Lobos","Lake Albert Tiger"],
      [7,"BU","Junee Grey","South Wagga Gladiators"],
      [8,"B1","South Wagga Knights","Junee Yellow"],
      [8,"B2","Henwood Park Hawks","Lake Albert Pointer"],
      [8,"B3","Henwood Park BlackHawks","Lake Albert Bull"],
      [8,"B4","Wagga United Crows","Lake Albert Tiger"],
      [8,"B6","Tolland Lobos","South Wagga Gladiators"],
      [8,"B7","Tolland Grey Wolves","Junee Grey"],
      [9,"B1","South Wagga Knights","Lake Albert Pointer"],
      [9,"BU","Junee Yellow","Lake Albert Bull"],
      [9,"B3","Henwood Park Hawks","Lake Albert Tiger"],
      [9,"B5","Wagga United Crows","South Wagga Gladiators"],
      [9,"BU","Junee Grey","Tolland Cubs"],
      [9,"B7","Tolland Lobos","Tolland Grey Wolves"],
      [10,"B1","South Wagga Knights","Lake Albert Bull"],
      [10,"B2","Lake Albert Pointer","Lake Albert Tiger"],
      [10,"B4","Henwood Park Hawks","South Wagga Gladiators"],
      [10,"B5","Henwood Park BlackHawks","Junee Grey"],
      [10,"B6","Wagga United Crows","Tolland Grey Wolves"],
      [10,"B7","Tolland Cubs","Tolland Lobos"],
      [11,"B1","South Wagga Knights","Lake Albert Tiger"],
      [11,"B3","Lake Albert Pointer","South Wagga Gladiators"],
      [11,"BU","Junee Yellow","Junee Grey"],
      [11,"B5","Henwood Park Hawks","Tolland Grey Wolves"],
      [11,"B6","Henwood Park BlackHawks","Tolland Lobos"],
      [11,"B7","Wagga United Crows","Tolland Cubs"],
      [12,"B2","Lake Albert Tiger","South Wagga Gladiators"],
      [12,"B3","Lake Albert Bull","Junee Grey"],
      [12,"B4","Lake Albert Pointer","Tolland Grey Wolves"],
      [12,"B5","Junee Yellow","Tolland Lobos"],
      [12,"B6","Henwood Park Hawks","Tolland Cubs"],
      [12,"B7","Henwood Park BlackHawks","Wagga United Crows"],
      [13,"B1","South Wagga Knights","South Wagga Gladiators"],
      [13,"B3","Lake Albert Tiger","Tolland Grey Wolves"],
      [13,"B4","Lake Albert Bull","Tolland Lobos"],
      [13,"B5","Lake Albert Pointer","Tolland Cubs"],
      [13,"BU","Junee Yellow","Wagga United Crows"],
      [13,"B7","Henwood Park Hawks","Henwood Park BlackHawks"],
      [14,"B1","South Wagga Knights","Junee Grey"],
      [14,"B2","South Wagga Gladiators","Tolland Grey Wolves"],
      [14,"B4","Lake Albert Tiger","Tolland Cubs"],
      [14,"B5","Lake Albert Bull","Wagga United Crows"],
      [14,"B6","Lake Albert Pointer","Henwood Park BlackHawks"],
      [14,"B7","Junee Yellow","Henwood Park Hawks"],
      [15,"B1","South Wagga Knights","Tolland Grey Wolves"],
      [15,"BU","Junee Grey","Tolland Lobos"],
      [15,"B3","South Wagga Gladiators","Tolland Cubs"],
      [15,"B5","Lake Albert Tiger","Henwood Park BlackHawks"],
      [15,"B6","Lake Albert Bull","Henwood Park Hawks"],
      [15,"BU","Junee Yellow","Lake Albert Pointer"],
    ]
  );

  // --- 7. U7/8 Girls ---
  await seedComp(
    "fww-u78-girls","U7/8 Girls","U8","FEMALE","13:15","B10",
    ["South Wagga Warriors","South Wagga Vikings","Tumut Gold","Tumut Red","Wagga United Queenfishers","Wagga United Robins","Henwood Park Superstars","Henwood Park Hawks","Lake Albert Mako Sharks","Lake Albert Bull Sharks","Lake Albert White Shark"],
    [
      [1,"B10","South Wagga Vikings","Wagga United Queenfishers"],
      [1,"B11","Tumut Gold","Wagga United Robins"],
      [1,"B12","Tumut Red","Henwood Park Superstars"],
      [1,"B13","Lake Albert Mako Sharks","Henwood Park Hawks"],
      [1,"B14","Lake Albert Bull Sharks","Lake Albert White Shark"],
      [2,"B10","South Wagga Warriors","Wagga United Queenfishers"],
      [2,"B11","South Wagga Vikings","Henwood Park Superstars"],
      [2,"TP","Tumut Gold","Henwood Park Hawks"],
      [2,"TP","Tumut Red","Lake Albert White Shark"],
      [2,"B14","Lake Albert Mako Sharks","Lake Albert Bull Sharks"],
      [3,"B10","South Wagga Warriors","Wagga United Robins"],
      [3,"B11","Wagga United Queenfishers","Henwood Park Superstars"],
      [3,"B12","South Wagga Vikings","Lake Albert White Shark"],
      [3,"B13","Tumut Gold","Lake Albert Bull Sharks"],
      [3,"B14","Tumut Red","Lake Albert Mako Sharks"],
      [4,"B10","South Wagga Warriors","Henwood Park Superstars"],
      [4,"B11","Wagga United Robins","Henwood Park Hawks"],
      [4,"B12","Wagga United Queenfishers","Lake Albert White Shark"],
      [4,"B13","South Wagga Vikings","Lake Albert Mako Sharks"],
      [4,"TP","Tumut Gold","Tumut Red"],
      [5,"B10","South Wagga Warriors","Henwood Park Hawks"],
      [5,"B11","Henwood Park Superstars","Lake Albert White Shark"],
      [5,"B12","Wagga United Robins","Lake Albert Bull Sharks"],
      [5,"B13","Wagga United Queenfishers","Lake Albert Mako Sharks"],
      [5,"B14","South Wagga Vikings","Tumut Gold"],
      [6,"B10","South Wagga Warriors","Lake Albert White Shark"],
      [6,"B11","Henwood Park Hawks","Lake Albert Bull Sharks"],
      [6,"B12","Henwood Park Superstars","Lake Albert Mako Sharks"],
      [6,"TP","Tumut Red","Wagga United Robins"],
      [6,"TP","Tumut Gold","Wagga United Queenfishers"],
      [7,"B10","South Wagga Warriors","Lake Albert Bull Sharks"],
      [7,"B11","Lake Albert White Shark","Lake Albert Mako Sharks"],
      [7,"B12","Henwood Park Hawks","Tumut Red"],
      [7,"B13","Henwood Park Superstars","Tumut Gold"],
      [7,"B14","Wagga United Robins","South Wagga Vikings"],
      [8,"B10","South Wagga Warriors","Lake Albert Mako Sharks"],
      [8,"TP","Tumut Red","Lake Albert Bull Sharks"],
      [8,"TP","Tumut Gold","Lake Albert White Shark"],
      [8,"B13","Henwood Park Hawks","South Wagga Vikings"],
      [8,"B14","Wagga United Robins","Wagga United Queenfishers"],
      [9,"B10","South Wagga Warriors","Tumut Red"],
      [9,"B11","Lake Albert Mako Sharks","Tumut Gold"],
      [9,"B12","Lake Albert Bull Sharks","South Wagga Vikings"],
      [9,"B13","Henwood Park Hawks","Wagga United Queenfishers"],
      [9,"B14","Henwood Park Superstars","Wagga United Robins"],
      [10,"TP","Tumut Gold","South Wagga Warriors"],
      [10,"TP","Tumut Red","South Wagga Vikings"],
      [10,"B12","Lake Albert Bull Sharks","Wagga United Queenfishers"],
      [10,"B13","Lake Albert White Shark","Wagga United Robins"],
      [10,"B14","Henwood Park Hawks","Henwood Park Superstars"],
      [11,"B10","South Wagga Warriors","South Wagga Vikings"],
      [11,"B11","Tumut Red","Wagga United Queenfishers"],
      [11,"B12","Lake Albert Mako Sharks","Wagga United Robins"],
      [11,"B13","Lake Albert Bull Sharks","Henwood Park Superstars"],
      [11,"B14","Lake Albert White Shark","Henwood Park Hawks"],
      [12,"B10","South Wagga Vikings","Wagga United Queenfishers"],
      [12,"TP","Tumut Gold","Wagga United Robins"],
      [12,"TP","Tumut Red","Henwood Park Superstars"],
      [12,"B13","Lake Albert Mako Sharks","Henwood Park Hawks"],
      [12,"B14","Lake Albert Bull Sharks","Lake Albert White Shark"],
      [13,"B10","South Wagga Warriors","Wagga United Queenfishers"],
      [13,"B11","South Wagga Vikings","Henwood Park Superstars"],
      [13,"B12","Tumut Gold","Henwood Park Hawks"],
      [13,"B13","Tumut Red","Lake Albert White Shark"],
      [13,"B14","Lake Albert Mako Sharks","Lake Albert Bull Sharks"],
      [14,"B10","South Wagga Warriors","Wagga United Robins"],
      [14,"B11","Wagga United Queenfishers","Henwood Park Superstars"],
      [14,"B12","South Wagga Vikings","Lake Albert White Shark"],
      [14,"TP","Tumut Gold","Lake Albert Bull Sharks"],
      [14,"TP","Tumut Red","Lake Albert Mako Sharks"],
      [15,"B10","South Wagga Warriors","Henwood Park Superstars"],
      [15,"B11","Wagga United Robins","Henwood Park Hawks"],
      [15,"B12","Wagga United Queenfishers","Lake Albert White Shark"],
      [15,"B13","South Wagga Vikings","Lake Albert Mako Sharks"],
      [15,"B14","Tumut Gold","Tumut Red"],
    ]
  );

  // --- 8. U8 Black ---
  await seedComp(
    "fww-u8-black","U8 Black","U8","MIXED","11:15","B10",
    ["South Wagga Vikings","Tolland Cubs","Lake Albert Red","Tolland Pups","Lake Albert Bull","Wagga United Rooks","Lake Albert White","Wagga United Ravens","Henwood Park Hawks","Henwood Park Falcons"],
    [
      [1,"B10","South Wagga Vikings","Tolland Cubs"],
      [1,"B11","Lake Albert Red","Tolland Pups"],
      [1,"B12","Lake Albert Bull","Wagga United Rooks"],
      [1,"B13","Lake Albert White","Wagga United Ravens"],
      [1,"B14","Henwood Park Hawks","Henwood Park Falcons"],
      [2,"B10","South Wagga Vikings","Tolland Pups"],
      [2,"B11","Tolland Cubs","Wagga United Rooks"],
      [2,"B12","Lake Albert Red","Wagga United Ravens"],
      [2,"B13","Lake Albert Bull","Henwood Park Falcons"],
      [2,"B14","Lake Albert White","Henwood Park Hawks"],
      [3,"B10","South Wagga Vikings","Wagga United Rooks"],
      [3,"B11","Tolland Pups","Wagga United Ravens"],
      [3,"B12","Tolland Cubs","Henwood Park Falcons"],
      [3,"B13","Lake Albert Red","Henwood Park Hawks"],
      [3,"B14","Lake Albert Bull","Lake Albert White"],
      [4,"B10","South Wagga Vikings","Wagga United Ravens"],
      [4,"B11","Wagga United Rooks","Henwood Park Falcons"],
      [4,"B12","Tolland Pups","Henwood Park Hawks"],
      [4,"B13","Tolland Cubs","Lake Albert White"],
      [4,"B14","Lake Albert Red","Lake Albert Bull"],
      [5,"B10","South Wagga Vikings","Henwood Park Falcons"],
      [5,"B11","Wagga United Ravens","Henwood Park Hawks"],
      [5,"B12","Wagga United Rooks","Lake Albert White"],
      [5,"B13","Tolland Pups","Lake Albert Bull"],
      [5,"B14","Tolland Cubs","Lake Albert Red"],
      [6,"B10","South Wagga Vikings","Henwood Park Hawks"],
      [6,"B11","Henwood Park Falcons","Lake Albert White"],
      [6,"B12","Wagga United Ravens","Lake Albert Bull"],
      [6,"B13","Wagga United Rooks","Lake Albert Red"],
      [6,"B14","Tolland Pups","Tolland Cubs"],
      [7,"B10","South Wagga Vikings","Lake Albert White"],
      [7,"B11","Henwood Park Hawks","Lake Albert Bull"],
      [7,"B12","Henwood Park Falcons","Lake Albert Red"],
      [7,"B13","Wagga United Ravens","Tolland Cubs"],
      [7,"B14","Wagga United Rooks","Tolland Pups"],
      [8,"B10","South Wagga Vikings","Lake Albert Bull"],
      [8,"B11","Lake Albert White","Lake Albert Red"],
      [8,"B12","Henwood Park Hawks","Tolland Cubs"],
      [8,"B13","Henwood Park Falcons","Tolland Pups"],
      [8,"B14","Wagga United Ravens","Wagga United Rooks"],
      [9,"B10","South Wagga Vikings","Lake Albert Red"],
      [9,"B11","Lake Albert Bull","Tolland Cubs"],
      [9,"B12","Lake Albert White","Tolland Pups"],
      [9,"B13","Henwood Park Hawks","Wagga United Rooks"],
      [9,"B14","Henwood Park Falcons","Wagga United Ravens"],
      [10,"B10","Tolland Cubs","South Wagga Vikings"],
      [10,"B11","Tolland Pups","Lake Albert Red"],
      [10,"B12","Wagga United Rooks","Lake Albert Bull"],
      [10,"B13","Wagga United Ravens","Lake Albert White"],
      [10,"B14","Henwood Park Falcons","Henwood Park Hawks"],
      [11,"B10","Tolland Pups","South Wagga Vikings"],
      [11,"B11","Wagga United Rooks","Tolland Cubs"],
      [11,"B12","Wagga United Ravens","Lake Albert Red"],
      [11,"B13","Henwood Park Falcons","Lake Albert Bull"],
      [11,"B14","Henwood Park Hawks","Lake Albert White"],
      [12,"B10","Wagga United Rooks","South Wagga Vikings"],
      [12,"B11","Wagga United Ravens","Tolland Pups"],
      [12,"B12","Henwood Park Falcons","Tolland Cubs"],
      [12,"B13","Henwood Park Hawks","Lake Albert Red"],
      [12,"B14","Lake Albert White","Lake Albert Bull"],
      [13,"B10","Wagga United Ravens","South Wagga Vikings"],
      [13,"B11","Henwood Park Falcons","Wagga United Rooks"],
      [13,"B12","Henwood Park Hawks","Tolland Pups"],
      [13,"B13","Lake Albert White","Tolland Cubs"],
      [13,"B14","Lake Albert Bull","Lake Albert Red"],
      [14,"B10","Henwood Park Falcons","South Wagga Vikings"],
      [14,"B11","Henwood Park Hawks","Wagga United Ravens"],
      [14,"B12","Lake Albert White","Wagga United Rooks"],
      [14,"B13","Lake Albert Bull","Tolland Pups"],
      [14,"B14","Lake Albert Red","Tolland Cubs"],
      [15,"B10","Henwood Park Hawks","South Wagga Vikings"],
      [15,"B11","Lake Albert White","Henwood Park Falcons"],
      [15,"B12","Lake Albert Bull","Wagga United Ravens"],
      [15,"B13","Lake Albert Red","Wagga United Rooks"],
      [15,"B14","Tolland Cubs","Tolland Pups"],
    ]
  );

  // --- 9. U8 White ---
  await seedComp(
    "fww-u8-white","U8 White","U8","MIXED","12:15","B10",
    ["South Wagga Warriors","Lake Albert Nurse Shark","Junee Blue","Lake Albert Pointer Sharks","Henwood Park Eagles","Henwood Park Raptors","Wagga United Crows","Wagga United Currawongs","Tolland Wolves","Tumut Gold"],
    [
      [1,"B10","South Wagga Warriors","Lake Albert Nurse Shark"],
      [1,"BU","Junee Blue","Lake Albert Pointer Sharks"],
      [1,"B12","Henwood Park Eagles","Henwood Park Raptors"],
      [1,"B13","Wagga United Crows","Wagga United Currawongs"],
      [1,"B14","Tolland Wolves","Tumut Gold"],
      [2,"B10","South Wagga Warriors","Junee Blue"],
      [2,"B11","Lake Albert Nurse Shark","Henwood Park Raptors"],
      [2,"B12","Lake Albert Pointer Sharks","Wagga United Currawongs"],
      [2,"TP","Henwood Park Eagles","Tumut Gold"],
      [2,"B14","Wagga United Crows","Tolland Wolves"],
      [3,"B10","South Wagga Warriors","Henwood Park Raptors"],
      [3,"BU","Junee Blue","Wagga United Currawongs"],
      [3,"B12","Lake Albert Nurse Shark","Tumut Gold"],
      [3,"B13","Lake Albert Pointer Sharks","Tolland Wolves"],
      [3,"B14","Henwood Park Eagles","Wagga United Crows"],
      [4,"B10","South Wagga Warriors","Wagga United Currawongs"],
      [4,"TP","Henwood Park Raptors","Tumut Gold"],
      [4,"B12","Junee Blue","Tolland Wolves"],
      [4,"B13","Lake Albert Nurse Shark","Wagga United Crows"],
      [4,"B14","Lake Albert Pointer Sharks","Henwood Park Eagles"],
      [5,"B10","South Wagga Warriors","Tumut Gold"],
      [5,"B11","Wagga United Currawongs","Tolland Wolves"],
      [5,"B12","Henwood Park Raptors","Wagga United Crows"],
      [5,"BU","Junee Blue","Henwood Park Eagles"],
      [5,"B14","Lake Albert Nurse Shark","Lake Albert Pointer Sharks"],
      [6,"B10","South Wagga Warriors","Tolland Wolves"],
      [6,"TP","Tumut Gold","Wagga United Crows"],
      [6,"B12","Wagga United Currawongs","Henwood Park Eagles"],
      [6,"B13","Henwood Park Raptors","Lake Albert Pointer Sharks"],
      [6,"B14","Junee Blue","Lake Albert Nurse Shark"],
      [7,"B10","South Wagga Warriors","Wagga United Crows"],
      [7,"B11","Tolland Wolves","Henwood Park Eagles"],
      [7,"B12","Tumut Gold","Lake Albert Pointer Sharks"],
      [7,"B13","Wagga United Currawongs","Lake Albert Nurse Shark"],
      [7,"BU","Junee Blue","Henwood Park Raptors"],
      [8,"B10","South Wagga Warriors","Henwood Park Eagles"],
      [8,"B11","Wagga United Crows","Lake Albert Pointer Sharks"],
      [8,"B12","Tolland Wolves","Lake Albert Nurse Shark"],
      [8,"TP","Tumut Gold","Junee Blue"],
      [8,"B14","Wagga United Currawongs","Henwood Park Raptors"],
      [9,"B10","South Wagga Warriors","Lake Albert Pointer Sharks"],
      [9,"B11","Henwood Park Eagles","Lake Albert Nurse Shark"],
      [9,"BU","Junee Blue","Wagga United Crows"],
      [9,"B13","Tolland Wolves","Henwood Park Raptors"],
      [9,"B14","Tumut Gold","Wagga United Currawongs"],
      [10,"B10","South Wagga Warriors","Lake Albert Nurse Shark"],
      [10,"B11","Lake Albert Pointer Sharks","Junee Blue"],
      [10,"B12","Henwood Park Eagles","Henwood Park Raptors"],
      [10,"B13","Wagga United Crows","Wagga United Currawongs"],
      [10,"TP","Tolland Wolves","Tumut Gold"],
      [11,"BU","Junee Blue","South Wagga Warriors"],
      [11,"B11","Lake Albert Nurse Shark","Henwood Park Raptors"],
      [11,"B12","Lake Albert Pointer Sharks","Wagga United Currawongs"],
      [11,"B13","Henwood Park Eagles","Tumut Gold"],
      [11,"B14","Wagga United Crows","Tolland Wolves"],
      [12,"B10","South Wagga Warriors","Henwood Park Raptors"],
      [12,"B11","Junee Blue","Wagga United Currawongs"],
      [12,"TP","Lake Albert Nurse Shark","Tumut Gold"],
      [12,"B13","Lake Albert Pointer Sharks","Tolland Wolves"],
      [12,"B14","Henwood Park Eagles","Wagga United Crows"],
      [13,"B10","South Wagga Warriors","Wagga United Currawongs"],
      [13,"B11","Henwood Park Raptors","Tumut Gold"],
      [13,"BU","Junee Blue","Tolland Wolves"],
      [13,"B13","Lake Albert Nurse Shark","Wagga United Crows"],
      [13,"B14","Lake Albert Pointer Sharks","Henwood Park Eagles"],
      [14,"TP","South Wagga Warriors","Tumut Gold"],
      [14,"B11","Wagga United Currawongs","Tolland Wolves"],
      [14,"B12","Henwood Park Raptors","Wagga United Crows"],
      [14,"B13","Junee Blue","Henwood Park Eagles"],
      [14,"B14","Lake Albert Nurse Shark","Lake Albert Pointer Sharks"],
      [15,"B10","South Wagga Warriors","Tolland Wolves"],
      [15,"B11","Tumut Gold","Wagga United Crows"],
      [15,"B12","Wagga United Currawongs","Henwood Park Eagles"],
      [15,"B13","Henwood Park Raptors","Lake Albert Pointer Sharks"],
      [15,"BU","Junee Blue","Lake Albert Nurse Shark"],
    ]
  );

  // --- 10. U9 Black ---
  await seedComp(
    "fww-u9-black","U9 Black","U9","MIXED","09:15","B10",
    ["South Wagga Warriors","South Wagga Vikings","Tumut Red","Wagga United Swifts","Lake Albert Red","Lake Albert Black","Wagga United Crows","Henwood Park Eagles","Henwood Park Raptors","Junee Blue","Tolland Wolves"],
    [
      [1,"B10","South Wagga Vikings","Tolland Wolves"],
      [1,"B11","Tumut Red","Wagga United Swifts"],
      [1,"B12","Lake Albert Red","Wagga United Crows"],
      [1,"B13","Lake Albert Black","Henwood Park Eagles"],
      [1,"BU","Junee Blue","Henwood Park Raptors"],
      [2,"B10","South Wagga Warriors","Tolland Wolves"],
      [2,"B11","South Wagga Vikings","Wagga United Crows"],
      [2,"TP","Tumut Red","Henwood Park Eagles"],
      [2,"B13","Lake Albert Red","Henwood Park Raptors"],
      [2,"B14","Lake Albert Black","Junee Blue"],
      [3,"B10","South Wagga Warriors","Wagga United Swifts"],
      [3,"B11","Tolland Wolves","Wagga United Crows"],
      [3,"B12","South Wagga Vikings","Henwood Park Raptors"],
      [3,"BU","Tumut Red","Junee Blue"],
      [3,"B14","Lake Albert Red","Lake Albert Black"],
      [4,"B10","South Wagga Warriors","Wagga United Crows"],
      [4,"B11","Wagga United Swifts","Henwood Park Eagles"],
      [4,"B12","Tolland Wolves","Henwood Park Raptors"],
      [4,"B13","South Wagga Vikings","Lake Albert Black"],
      [4,"TP","Tumut Red","Lake Albert Red"],
      [5,"B10","South Wagga Warriors","Henwood Park Eagles"],
      [5,"B11","Wagga United Crows","Henwood Park Raptors"],
      [5,"BU","Junee Blue","Wagga United Swifts"],
      [5,"B13","Tolland Wolves","Lake Albert Black"],
      [5,"B14","South Wagga Vikings","Tumut Red"],
      [6,"B10","South Wagga Warriors","Henwood Park Raptors"],
      [6,"B11","Henwood Park Eagles","Junee Blue"],
      [6,"B12","Wagga United Crows","Lake Albert Black"],
      [6,"B13","Wagga United Swifts","Lake Albert Red"],
      [6,"TP","Tumut Red","Tolland Wolves"],
      [7,"BU","Junee Blue","South Wagga Warriors"],
      [7,"B11","Henwood Park Raptors","Lake Albert Black"],
      [7,"B12","Henwood Park Eagles","Lake Albert Red"],
      [7,"B13","Wagga United Crows","Tumut Red"],
      [7,"B14","Wagga United Swifts","South Wagga Vikings"],
      [8,"B10","South Wagga Warriors","Lake Albert Black"],
      [8,"B11","Junee Blue","Lake Albert Red"],
      [8,"TP","Tumut Red","Henwood Park Raptors"],
      [8,"B13","Henwood Park Eagles","South Wagga Vikings"],
      [8,"B14","Wagga United Swifts","Tolland Wolves"],
      [9,"B10","South Wagga Warriors","Lake Albert Red"],
      [9,"B11","Lake Albert Black","Tumut Red"],
      [9,"BU","Junee Blue","South Wagga Vikings"],
      [9,"B13","Henwood Park Eagles","Tolland Wolves"],
      [9,"B14","Wagga United Crows","Wagga United Swifts"],
      [10,"TP","Tumut Red","South Wagga Warriors"],
      [10,"B11","Lake Albert Red","South Wagga Vikings"],
      [10,"B12","Junee Blue","Tolland Wolves"],
      [10,"B13","Henwood Park Raptors","Wagga United Swifts"],
      [10,"B14","Henwood Park Eagles","Wagga United Crows"],
      [11,"B10","South Wagga Warriors","South Wagga Vikings"],
      [11,"B11","Lake Albert Red","Tolland Wolves"],
      [11,"B12","Lake Albert Black","Wagga United Swifts"],
      [11,"BU","Junee Blue","Wagga United Crows"],
      [11,"B14","Henwood Park Raptors","Henwood Park Eagles"],
      [12,"B10","South Wagga Vikings","Tolland Wolves"],
      [12,"TP","Tumut Red","Wagga United Swifts"],
      [12,"B12","Lake Albert Red","Wagga United Crows"],
      [12,"B13","Lake Albert Black","Henwood Park Eagles"],
      [12,"B14","Junee Blue","Henwood Park Raptors"],
      [13,"B10","South Wagga Warriors","Tolland Wolves"],
      [13,"B11","South Wagga Vikings","Wagga United Crows"],
      [13,"B12","Tumut Red","Henwood Park Eagles"],
      [13,"B13","Lake Albert Red","Henwood Park Raptors"],
      [13,"BU","Junee Blue","Lake Albert Black"],
      [14,"B10","South Wagga Warriors","Wagga United Swifts"],
      [14,"B11","Tolland Wolves","Wagga United Crows"],
      [14,"B12","South Wagga Vikings","Henwood Park Raptors"],
      [14,"TP","Tumut Red","Junee Blue"],
      [14,"B14","Lake Albert Red","Lake Albert Black"],
      [15,"B10","South Wagga Warriors","Wagga United Crows"],
      [15,"B11","Wagga United Swifts","Henwood Park Eagles"],
      [15,"B12","Tolland Wolves","Henwood Park Raptors"],
      [15,"B13","South Wagga Vikings","Lake Albert Black"],
      [15,"B14","Tumut Red","Lake Albert Red"],
    ]
  );

  // --- 11. U9 White ---
  await seedComp(
    "fww-u9-white","U9 White","U9","MIXED","10:15","B10",
    ["South Wagga Knights","Tumut Gold","Lake Albert White","Lake Albert Mako Sharks","Lake Albert Pointer Sharks","Junee Yellow","Tolland Pups","Tolland Cubs","Wagga United Rooks","Henwood Park Blackhawks","Henwood Park Hawks","Lake Albert Tiger Sharks"],
    [
      [1,"B10","South Wagga Knights","Tolland Pups"],
      [1,"B11","Tumut Gold","Tolland Cubs"],
      [1,"B12","Lake Albert White","Wagga United Rooks"],
      [1,"B13","Lake Albert Mako Sharks","Henwood Park Blackhawks"],
      [1,"B14","Lake Albert Pointer Sharks","Henwood Park Hawks"],
      [1,"BU","Junee Yellow","Lake Albert Tiger Sharks"],
      [2,"B10","South Wagga Knights","Tolland Cubs"],
      [2,"B11","Tolland Pups","Wagga United Rooks"],
      [2,"TP","Tumut Gold","Henwood Park Blackhawks"],
      [2,"B13","Lake Albert White","Henwood Park Hawks"],
      [2,"B14","Lake Albert Mako Sharks","Junee Yellow"],
      [2,"B15","Lake Albert Pointer Sharks","Lake Albert Tiger Sharks"],
      [3,"B10","South Wagga Knights","Wagga United Rooks"],
      [3,"B11","Tolland Cubs","Henwood Park Blackhawks"],
      [3,"B12","Tolland Pups","Henwood Park Hawks"],
      [3,"BU","Junee Yellow","Tumut Gold"],
      [3,"B14","Lake Albert White","Lake Albert Tiger Sharks"],
      [3,"B15","Lake Albert Mako Sharks","Lake Albert Pointer Sharks"],
      [4,"B10","South Wagga Knights","Henwood Park Blackhawks"],
      [4,"B11","Wagga United Rooks","Henwood Park Hawks"],
      [4,"B12","Tolland Cubs","Junee Yellow"],
      [4,"B13","Tolland Pups","Lake Albert Tiger Sharks"],
      [4,"TP","Tumut Gold","Lake Albert Pointer Sharks"],
      [4,"B15","Lake Albert White","Lake Albert Mako Sharks"],
      [5,"B10","South Wagga Knights","Henwood Park Hawks"],
      [5,"BU","Junee Yellow","Henwood Park Blackhawks"],
      [5,"B12","Wagga United Rooks","Lake Albert Tiger Sharks"],
      [5,"B13","Tolland Cubs","Lake Albert Pointer Sharks"],
      [5,"B14","Tolland Pups","Lake Albert Mako Sharks"],
      [5,"B15","Tumut Gold","Lake Albert White"],
      [6,"B10","South Wagga Knights","Junee Yellow"],
      [6,"B11","Henwood Park Hawks","Lake Albert Tiger Sharks"],
      [6,"B12","Henwood Park Blackhawks","Lake Albert Pointer Sharks"],
      [6,"B13","Wagga United Rooks","Lake Albert Mako Sharks"],
      [6,"B14","Tolland Cubs","Lake Albert White"],
      [6,"TP","Tumut Gold","Tolland Pups"],
      [7,"B10","South Wagga Knights","Lake Albert Tiger Sharks"],
      [7,"BU","Junee Yellow","Lake Albert Pointer Sharks"],
      [7,"B12","Henwood Park Hawks","Lake Albert Mako Sharks"],
      [7,"B13","Henwood Park Blackhawks","Lake Albert White"],
      [7,"B14","Wagga United Rooks","Tumut Gold"],
      [7,"B15","Tolland Cubs","Tolland Pups"],
      [8,"B10","South Wagga Knights","Lake Albert Pointer Sharks"],
      [8,"B11","Lake Albert Tiger Sharks","Lake Albert Mako Sharks"],
      [8,"B12","Junee Yellow","Lake Albert White"],
      [8,"TP","Tumut Gold","Henwood Park Hawks"],
      [8,"B14","Henwood Park Blackhawks","Tolland Pups"],
      [8,"B15","Wagga United Rooks","Tolland Cubs"],
      [9,"B10","South Wagga Knights","Lake Albert Mako Sharks"],
      [9,"B11","Lake Albert Pointer Sharks","Lake Albert White"],
      [9,"B12","Lake Albert Tiger Sharks","Tumut Gold"],
      [9,"BU","Junee Yellow","Tolland Pups"],
      [9,"B14","Henwood Park Hawks","Tolland Cubs"],
      [9,"B15","Henwood Park Blackhawks","Wagga United Rooks"],
      [10,"B10","South Wagga Knights","Lake Albert White"],
      [10,"TP","Tumut Gold","Lake Albert Mako Sharks"],
      [10,"B12","Lake Albert Pointer Sharks","Tolland Pups"],
      [10,"B13","Lake Albert Tiger Sharks","Tolland Cubs"],
      [10,"B14","Junee Yellow","Wagga United Rooks"],
      [10,"B15","Henwood Park Hawks","Henwood Park Blackhawks"],
      [11,"B10","South Wagga Knights","Tumut Gold"],
      [11,"B11","Lake Albert White","Tolland Pups"],
      [11,"B12","Lake Albert Mako Sharks","Tolland Cubs"],
      [11,"B13","Lake Albert Pointer Sharks","Wagga United Rooks"],
      [11,"B14","Lake Albert Tiger Sharks","Henwood Park Blackhawks"],
      [11,"BU","Junee Yellow","Henwood Park Hawks"],
      [12,"B10","South Wagga Knights","Tolland Pups"],
      [12,"TP","Tumut Gold","Tolland Cubs"],
      [12,"B12","Lake Albert White","Wagga United Rooks"],
      [12,"B13","Lake Albert Mako Sharks","Henwood Park Blackhawks"],
      [12,"B14","Lake Albert Pointer Sharks","Henwood Park Hawks"],
      [12,"B15","Lake Albert Tiger Sharks","Junee Yellow"],
      [13,"B10","South Wagga Knights","Tolland Cubs"],
      [13,"B11","Tolland Pups","Wagga United Rooks"],
      [13,"B12","Tumut Gold","Henwood Park Blackhawks"],
      [13,"B13","Lake Albert White","Henwood Park Hawks"],
      [13,"BU","Junee Yellow","Lake Albert Mako Sharks"],
      [13,"B15","Lake Albert Pointer Sharks","Lake Albert Tiger Sharks"],
      [14,"B10","South Wagga Knights","Wagga United Rooks"],
      [14,"B11","Tolland Cubs","Henwood Park Blackhawks"],
      [14,"B12","Tolland Pups","Henwood Park Hawks"],
      [14,"TP","Tumut Gold","Junee Yellow"],
      [14,"B14","Lake Albert White","Lake Albert Tiger Sharks"],
      [14,"B15","Lake Albert Mako Sharks","Lake Albert Pointer Sharks"],
      [15,"B10","South Wagga Knights","Henwood Park Blackhawks"],
      [15,"B11","Wagga United Rooks","Henwood Park Hawks"],
      [15,"BU","Junee Yellow","Tolland Cubs"],
      [15,"B13","Tolland Pups","Lake Albert Tiger Sharks"],
      [15,"B14","Tumut Gold","Lake Albert Pointer Sharks"],
      [15,"B15","Lake Albert White","Lake Albert Mako Sharks"],
    ]
  );

  // --- 12. U10 Black ---
  await seedComp(
    "fww-u10-black","U10 Black","U10","MIXED","09:15","D1",
    ["South Wagga Warriors","Lake Albert Pointer Sharks","Lake Albert Red","Tolland Wolves","Wagga United Swifts","Henwood Park Hawks"],
    [
      [1,"D1","South Wagga Warriors","Tolland Wolves"],
      [1,"D2","Lake Albert Pointer Sharks","Wagga United Swifts"],
      [1,"D3","Lake Albert Red","Henwood Park Hawks"],
      [2,"D1","South Wagga Warriors","Wagga United Swifts"],
      [2,"D2","Tolland Wolves","Henwood Park Hawks"],
      [2,"D3","Lake Albert Pointer Sharks","Lake Albert Red"],
      [3,"D1","South Wagga Warriors","Henwood Park Hawks"],
      [3,"D2","Wagga United Swifts","Lake Albert Red"],
      [3,"D3","Tolland Wolves","Lake Albert Pointer Sharks"],
      [4,"D1","South Wagga Warriors","Lake Albert Red"],
      [4,"D2","Henwood Park Hawks","Lake Albert Pointer Sharks"],
      [4,"D3","Wagga United Swifts","Tolland Wolves"],
      [5,"D1","South Wagga Warriors","Lake Albert Pointer Sharks"],
      [5,"D2","Lake Albert Red","Tolland Wolves"],
      [5,"D3","Henwood Park Hawks","Wagga United Swifts"],
      [6,"D1","South Wagga Warriors","Tolland Wolves"],
      [6,"D2","Lake Albert Pointer Sharks","Wagga United Swifts"],
      [6,"D3","Lake Albert Red","Henwood Park Hawks"],
      [7,"D1","South Wagga Warriors","Wagga United Swifts"],
      [7,"D2","Tolland Wolves","Henwood Park Hawks"],
      [7,"D3","Lake Albert Pointer Sharks","Lake Albert Red"],
      [8,"D1","South Wagga Warriors","Henwood Park Hawks"],
      [8,"D2","Wagga United Swifts","Lake Albert Red"],
      [8,"D3","Tolland Wolves","Lake Albert Pointer Sharks"],
      [9,"D1","South Wagga Warriors","Lake Albert Red"],
      [9,"D2","Henwood Park Hawks","Lake Albert Pointer Sharks"],
      [9,"D3","Wagga United Swifts","Tolland Wolves"],
      [10,"D1","South Wagga Warriors","Lake Albert Pointer Sharks"],
      [10,"D2","Lake Albert Red","Tolland Wolves"],
      [10,"D3","Henwood Park Hawks","Wagga United Swifts"],
      [11,"D1","South Wagga Warriors","Tolland Wolves"],
      [11,"D2","Lake Albert Pointer Sharks","Wagga United Swifts"],
      [11,"D3","Lake Albert Red","Henwood Park Hawks"],
      [12,"D1","South Wagga Warriors","Wagga United Swifts"],
      [12,"D2","Tolland Wolves","Henwood Park Hawks"],
      [12,"D3","Lake Albert Pointer Sharks","Lake Albert Red"],
      [13,"D1","South Wagga Warriors","Henwood Park Hawks"],
      [13,"D2","Wagga United Swifts","Lake Albert Red"],
      [13,"D3","Tolland Wolves","Lake Albert Pointer Sharks"],
      [14,"D1","South Wagga Warriors","Lake Albert Red"],
      [14,"D2","Henwood Park Hawks","Lake Albert Pointer Sharks"],
      [14,"D3","Wagga United Swifts","Tolland Wolves"],
      [15,"D1","South Wagga Warriors","Lake Albert Pointer Sharks"],
      [15,"D2","Lake Albert Red","Tolland Wolves"],
      [15,"D3","Henwood Park Hawks","Wagga United Swifts"],
    ]
  );

  // --- 13. U10 White ---
  await seedComp(
    "fww-u10-white","U10 White","U10","MIXED","10:15","D1",
    ["South Wagga Vikings","Tumut Gold","Lake Albert White Sharks","Junee Blue","Lake Albert Tiger Sharks","South Wagga Knight","Wagga United Currawongs","Henwood Park Raptors","Henwood Park Falcons","Lake Albert Bull Sharks","Lake Albert Black Sharks"],
    [
      [1,"D1","South Wagga Vikings","Wagga United Currawongs"],
      [1,"D2","Tumut Gold","Henwood Park Raptors"],
      [1,"D3","Lake Albert White Sharks","Henwood Park Falcons"],
      [1,"BU","Junee Blue","Lake Albert Bull Sharks"],
      [1,"D5","Lake Albert Tiger Sharks","Lake Albert Black Sharks"],
      [2,"D1","South Wagga Knight","Wagga United Currawongs"],
      [2,"D2","South Wagga Vikings","Henwood Park Falcons"],
      [2,"TP","Tumut Gold","Junee Blue"],
      [2,"D4","Lake Albert White Sharks","Lake Albert Black Sharks"],
      [2,"D5","Lake Albert Bull Sharks","Lake Albert Tiger Sharks"],
      [3,"D1","South Wagga Knight","Henwood Park Raptors"],
      [3,"D2","Wagga United Currawongs","Henwood Park Falcons"],
      [3,"D3","South Wagga Vikings","Lake Albert Black Sharks"],
      [3,"D4","Tumut Gold","Lake Albert Tiger Sharks"],
      [3,"D5","Lake Albert White Sharks","Lake Albert Bull Sharks"],
      [4,"D1","South Wagga Knight","Henwood Park Falcons"],
      [4,"D2","Henwood Park Raptors","Junee Blue"],
      [4,"D3","Wagga United Currawongs","Lake Albert Black Sharks"],
      [4,"D4","South Wagga Vikings","Lake Albert Bull Sharks"],
      [4,"TP","Tumut Gold","Lake Albert White Sharks"],
      [5,"BU","Junee Blue","South Wagga Knight"],
      [5,"D2","Henwood Park Falcons","Lake Albert Black Sharks"],
      [5,"D3","Henwood Park Raptors","Lake Albert Tiger Sharks"],
      [5,"D4","Wagga United Currawongs","Lake Albert Bull Sharks"],
      [5,"D5","South Wagga Vikings","Tumut Gold"],
      [6,"D1","South Wagga Knight","Lake Albert Black Sharks"],
      [6,"D2","Junee Blue","Lake Albert Tiger Sharks"],
      [6,"D3","Henwood Park Falcons","Lake Albert Bull Sharks"],
      [6,"D4","Henwood Park Raptors","Lake Albert White Sharks"],
      [6,"TP","Tumut Gold","Wagga United Currawongs"],
      [7,"D1","South Wagga Knight","Lake Albert Tiger Sharks"],
      [7,"D2","Lake Albert Black Sharks","Lake Albert Bull Sharks"],
      [7,"BU","Junee Blue","Lake Albert White Sharks"],
      [7,"D4","Henwood Park Falcons","Tumut Gold"],
      [7,"D5","Henwood Park Raptors","South Wagga Vikings"],
      [8,"D1","South Wagga Knight","Lake Albert Bull Sharks"],
      [8,"D2","Lake Albert Tiger Sharks","Lake Albert White Sharks"],
      [8,"TP","Tumut Gold","Lake Albert Black Sharks"],
      [8,"D4","Junee Blue","South Wagga Vikings"],
      [8,"D5","Henwood Park Raptors","Wagga United Currawongs"],
      [9,"D1","South Wagga Knight","Lake Albert White Sharks"],
      [9,"D2","Lake Albert Bull Sharks","Tumut Gold"],
      [9,"D3","Lake Albert Tiger Sharks","South Wagga Vikings"],
      [9,"BU","Junee Blue","Wagga United Currawongs"],
      [9,"D5","Henwood Park Falcons","Henwood Park Raptors"],
      [10,"TP","Tumut Gold","South Wagga Knight"],
      [10,"D2","Lake Albert White Sharks","South Wagga Vikings"],
      [10,"D3","Lake Albert Tiger Sharks","Wagga United Currawongs"],
      [10,"D4","Lake Albert Black Sharks","Henwood Park Raptors"],
      [10,"D5","Junee Blue","Henwood Park Falcons"],
      [11,"D1","South Wagga Knight","South Wagga Vikings"],
      [11,"D2","Lake Albert White Sharks","Wagga United Currawongs"],
      [11,"D3","Lake Albert Bull Sharks","Henwood Park Raptors"],
      [11,"D4","Lake Albert Tiger Sharks","Henwood Park Falcons"],
      [11,"BU","Junee Blue","Lake Albert Black Sharks"],
      [12,"D1","South Wagga Vikings","Wagga United Currawongs"],
      [12,"TP","Tumut Gold","Henwood Park Raptors"],
      [12,"D3","Lake Albert White Sharks","Henwood Park Falcons"],
      [12,"D4","Lake Albert Bull Sharks","Junee Blue"],
      [12,"D5","Lake Albert Tiger Sharks","Lake Albert Black Sharks"],
      [13,"D1","South Wagga Knight","Wagga United Currawongs"],
      [13,"D2","South Wagga Vikings","Henwood Park Falcons"],
      [13,"BU","Junee Blue","Tumut Gold"],
      [13,"D4","Lake Albert White Sharks","Lake Albert Black Sharks"],
      [13,"D5","Lake Albert Bull Sharks","Lake Albert Tiger Sharks"],
      [14,"D1","South Wagga Knight","Henwood Park Raptors"],
      [14,"D2","Wagga United Currawongs","Henwood Park Falcons"],
      [14,"D3","South Wagga Vikings","Lake Albert Black Sharks"],
      [14,"TP","Tumut Gold","Lake Albert Tiger Sharks"],
      [14,"D5","Lake Albert White Sharks","Lake Albert Bull Sharks"],
      [15,"D1","South Wagga Knight","Henwood Park Falcons"],
      [15,"BU","Junee Blue","Henwood Park Raptors"],
      [15,"D3","Wagga United Currawongs","Lake Albert Black Sharks"],
      [15,"D4","South Wagga Vikings","Lake Albert Bull Sharks"],
      [15,"D5","Tumut Gold","Lake Albert White Sharks"],
    ]
  );

  // --- 14. U9/10 Girls ---
  await seedComp(
    "fww-u910-girls","U9/10 Girls","U10","FEMALE","08:15","D1",
    ["South Wagga Warriors","South Wagga Vikings","Wagga United Kingfishers","Lake Albert Ninja Sharks","Henwood Park Hawks","Henwood Park Falcons","Lake Albert Red"],
    [
      [1,"D1","South Wagga Vikings","Henwood Park Hawks"],
      [1,"D2","Wagga United Kingfishers","Henwood Park Falcons"],
      [1,"D3","Lake Albert Ninja Sharks","Lake Albert Red"],
      [2,"D1","South Wagga Warriors","Henwood Park Hawks"],
      [2,"D2","South Wagga Vikings","Lake Albert Red"],
      [2,"D3","Wagga United Kingfishers","Lake Albert Ninja Sharks"],
      [3,"D1","South Wagga Warriors","Henwood Park Falcons"],
      [3,"D2","Henwood Park Hawks","Lake Albert Red"],
      [3,"D3","South Wagga Vikings","Wagga United Kingfishers"],
      [4,"D1","South Wagga Warriors","Lake Albert Red"],
      [4,"D2","Henwood Park Falcons","Lake Albert Ninja Sharks"],
      [4,"D3","Henwood Park Hawks","Wagga United Kingfishers"],
      [5,"D1","South Wagga Warriors","Lake Albert Ninja Sharks"],
      [5,"D2","Lake Albert Red","Wagga United Kingfishers"],
      [5,"D3","Henwood Park Falcons","South Wagga Vikings"],
      [6,"D1","South Wagga Warriors","Wagga United Kingfishers"],
      [6,"D2","Lake Albert Ninja Sharks","South Wagga Vikings"],
      [6,"D3","Henwood Park Falcons","Henwood Park Hawks"],
      [7,"D1","South Wagga Warriors","South Wagga Vikings"],
      [7,"D2","Lake Albert Ninja Sharks","Henwood Park Hawks"],
      [7,"D3","Lake Albert Red","Henwood Park Falcons"],
      [8,"D1","South Wagga Vikings","Henwood Park Hawks"],
      [8,"D2","Wagga United Kingfishers","Henwood Park Falcons"],
      [8,"D3","Lake Albert Ninja Sharks","Lake Albert Red"],
      [9,"D1","South Wagga Warriors","Henwood Park Hawks"],
      [9,"D2","South Wagga Vikings","Lake Albert Red"],
      [9,"D3","Wagga United Kingfishers","Lake Albert Ninja Sharks"],
      [10,"D1","South Wagga Warriors","Henwood Park Falcons"],
      [10,"D2","Henwood Park Hawks","Lake Albert Red"],
      [10,"D3","South Wagga Vikings","Wagga United Kingfishers"],
      [11,"D1","South Wagga Warriors","Lake Albert Red"],
      [11,"D2","Henwood Park Falcons","Lake Albert Ninja Sharks"],
      [11,"D3","Henwood Park Hawks","Wagga United Kingfishers"],
      [12,"D1","South Wagga Warriors","Lake Albert Ninja Sharks"],
      [12,"D2","Lake Albert Red","Wagga United Kingfishers"],
      [12,"D3","Henwood Park Falcons","South Wagga Vikings"],
      [13,"D1","South Wagga Warriors","Wagga United Kingfishers"],
      [13,"D2","Lake Albert Ninja Sharks","South Wagga Vikings"],
      [13,"D3","Henwood Park Falcons","Henwood Park Hawks"],
      [14,"D1","South Wagga Warriors","South Wagga Vikings"],
      [14,"D2","Lake Albert Ninja Sharks","Henwood Park Hawks"],
      [14,"D3","Lake Albert Red","Henwood Park Falcons"],
      [15,"D1","South Wagga Vikings","Henwood Park Hawks"],
      [15,"D2","Wagga United Kingfishers","Henwood Park Falcons"],
      [15,"D3","Lake Albert Ninja Sharks","Lake Albert Red"],
    ]
  );

  // 4. DRIBL stub competitions
  for (const [id, name, ag, gen] of [
    ["fww-u1112-black", "U11-12 Black", "U12", "MIXED"],
    ["fww-u1112-grey",  "U11-12 Grey",  "U12", "MIXED"],
    ["fww-u1112-white", "U11-12 White", "U12", "MIXED"],
    ["fww-u1112-girls", "U11-12 Girls", "U12", "FEMALE"],
  ] as const) {
    await prisma.competition.upsert({
      where: { id }, update: {},
      create: { id, name, season: "2026", ageGroup: ag as any, gender: gen as any, status: "REGISTRATION" },
    });
  }

  // 5. FutsalSession records
  await prisma.futsalSession.upsert({
    where: { id: "fww-clinic-july26" }, update: {},
    create: {
      id: "fww-clinic-july26", title: "Winter Holiday Football Clinic",
      description: "Join us for skills training during the July school holidays.",
      scheduledAt: new Date("2026-07-14T09:00:00+10:00"),
      durationMins: 120, capacityMax: 40, priceCents: 2500, status: "OPEN",
    },
  });
  await prisma.futsalSession.upsert({
    where: { id: "fww-clinic-oct26" }, update: {},
    create: {
      id: "fww-clinic-oct26", title: "Spring Holiday Football Clinic",
      description: "Improve your skills during the October school holidays.",
      scheduledAt: new Date("2026-10-06T09:00:00+10:00"),
      durationMins: 120, capacityMax: 40, priceCents: 2500, status: "OPEN",
    },
  });

  // 6. RulesDocument
  await prisma.rulesDocument.upsert({
    where: { id: "fww-rules-miniroos" }, update: {},
    create: {
      id: "fww-rules-miniroos",
      title: "Football Wagga Miniroos Competition Rules 2026",
      content: `Football Wagga Miniroos 2026 Competition Rules\n\nThese rules follow the Football Australia Miniroos framework...`,
      version: "2026.1",
      active: true,
    },
  });
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
